"""Autostart / autostop helpers for the hermes-mine-bean cron mode.

We don't import Hermes' internal cron module because that would gate plugin
install on a specific Hermes version. Instead we:

1. Generate a wrapper shell script at $HERMES_HOME/scripts/minebean-mine.sh
   that sources ~/.hermes/.env (so cron's stripped env still gets credentials)
   and execs `hermes-minebean-deploy` with the desired flags.
2. Return the suggested `hermes cron add` command the user can copy-paste.
3. If `hermes` is on PATH, try to invoke it directly so the cron is created
   without manual intervention. Fall back to printing the command otherwise.

autostop mirrors that with `hermes cron remove`.
"""
from __future__ import annotations

import logging
import os
import shutil
import stat
import subprocess
from pathlib import Path
from typing import Any

from . import state

logger = logging.getLogger(__name__)


JOB_NAME = "MineBean deploy"
SCRIPT_BASENAME = "minebean-mine.sh"


def _scripts_dir() -> Path:
    d = state.hermes_home() / "scripts"
    d.mkdir(parents=True, exist_ok=True)
    return d


def wrapper_path() -> Path:
    return _scripts_dir() / SCRIPT_BASENAME


_WRAPPER_TEMPLATE = """#!/usr/bin/env bash
# auto-generated by hermes-mine-bean autostart. do not edit by hand.
set -euo pipefail

# Source the user's .env so cron's stripped env still has credentials.
ENV_FILE="${{HERMES_HOME:-$HOME/.hermes}}/.env"
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

exec hermes-minebean-deploy{profile_arg} --quiet
"""


def write_wrapper(profile: str | None = None) -> Path:
    """Write the cron wrapper script and chmod it executable.

    Returns the path. Overwrites any existing wrapper at the same location.
    """
    profile_arg = f" --profile {profile}" if profile else ""
    body = _WRAPPER_TEMPLATE.format(profile_arg=profile_arg)
    path = wrapper_path()
    path.write_text(body)
    # User-only rwx (0o700). The wrapper sources ~/.hermes/.env which may
    # contain MINEBEAN_DEPLOYER_KEY, so group/other access is not warranted.
    path.chmod(0o700)
    return path


def _hermes_on_path() -> bool:
    return shutil.which("hermes") is not None


def _hermes_command_for_autostart(wrapper: Path, schedule: str) -> list[str]:
    """Build the argv for `hermes cron add ...`.

    Hermes CLI shape (verified against installed version):
        hermes cron add --name NAME --no-agent --script PATH SCHEDULE
    `schedule` is a positional argument and MUST come after the flags.
    """
    return [
        "hermes",
        "cron",
        "add",
        "--name",
        JOB_NAME,
        "--no-agent",
        "--script",
        str(wrapper),
        schedule,
    ]


def _hermes_command_hint_for_autostop() -> str:
    """Hermes cron remove takes a job_id positional, not a name.

    We don't have the job_id without parsing `hermes cron list`, so the
    cleanest path is to print instructions for the user. They run two
    commands manually.
    """
    return (
        "hermes cron list  # find the job_id for 'MineBean deploy'\n"
        "hermes cron remove <job_id>  # paste the ID from above"
    )


def autostart(
    *,
    schedule: str = "every 60s",
    profile: str | None = None,
    daily_cap: int | None = None,
) -> dict[str, Any]:
    """Provision the cron job.

    Writes the wrapper, then either invokes `hermes cron add` directly if the
    binary is on PATH, or returns the suggested command for the user to run.

    daily_cap is informational here; the real cap lives in
    MINEBEAN_MAX_DEPLOYS_PER_DAY and is enforced by the cron entry on every
    fire. Passing it just echoes back the value so callers can confirm.
    """
    chosen_profile = (profile or "").strip().lower() or state.get_profile()
    wrapper = write_wrapper(profile=chosen_profile)
    cmd = _hermes_command_for_autostart(wrapper, schedule)
    suggested = " ".join(_quote(arg) for arg in cmd)

    result: dict[str, Any] = {
        "wrapper": str(wrapper),
        "schedule": schedule,
        "profile": chosen_profile,
        "daily_cap": daily_cap or state.get_daily_ceiling(),
        "suggested_command": suggested,
    }

    if _hermes_on_path():
        try:
            completed = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=15,
                check=False,
            )
            result["invoked"] = True
            result["returncode"] = completed.returncode
            result["stdout"] = completed.stdout.strip()
            result["stderr"] = completed.stderr.strip()
            result["created"] = completed.returncode == 0
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
            result["invoked"] = False
            result["created"] = False
            result["error"] = f"{type(exc).__name__}: {exc}"
    else:
        result["invoked"] = False
        result["created"] = False
        result["note"] = (
            "hermes binary not found on PATH. "
            "Run the suggested_command manually to install the cron job."
        )

    return result


def autostop() -> dict[str, Any]:
    """Return instructions for removing the cron job.

    Hermes' `cron remove` takes a job_id positional, not a name. Without
    parsing `hermes cron list` we can't auto-resolve the ID, so we return
    the two-step manual command. The wrapper script is left in place
    (harmless) for next autostart.
    """
    return {
        "wrapper": str(wrapper_path()),
        "removed": False,
        "invoked": False,
        "instructions": _hermes_command_hint_for_autostop(),
        "note": (
            "Hermes' cron remove requires a job_id, not the name. "
            "Run 'hermes cron list' to find the ID for 'MineBean deploy', "
            "then 'hermes cron remove <id>' to delete it."
        ),
    }


def _quote(arg: str) -> str:
    """Minimal shell quoting for the suggested command display."""
    if not arg or any(c in arg for c in " \t\n\"'\\$`"):
        return "'" + arg.replace("'", "'\\''") + "'"
    return arg
